
* введение
    + понятие факта
    + описание
      + качественное
      + количественное



* методы:
** общие
  + наблюдение
    + виды
      + прямое
      + косвенное
      + непосредатственное
      + опосредованное
    + феноменолизм
    + ноуменализм
    + принцип наблюдаемости
  + измерение
    + прямое
    + косвенное
    + эталон
    + виды шкал
  + эксперимент
    + виды
    + ослабление несущественных факторов


** социально-гуманитарные
  + идиографический
  + диалог
  + понимание
  + интроспекция
  + эмпатия
  + тестирование, вопросы и интервью
  + проективные методы
  + биографический и автобиографический методы
  + социальный эксперимент и социальное моделирование
  + ролевые и имитационные игры

* Теоретическая нагруженность эмпирического познания

* materials:
  + http://science_philosophy.academic.ru/468/%D0%AD%D0%9C%D0%9F%D0%98%D0%A0%D0%98%D0%A7%D0%95%D0%A1%D0%9A%D0%98%D0%95_%D0%9C%D0%95%D0%A2%D0%9E%D0%94%D0%AB_%D0%9D%D0%90%D0%A3%D0%A7%D0%9D%D0%9E%D0%93%D0%9E_%D0%9F%D0%9E%D0%97%D0%9D%D0%90%D0%9D%D0%98%D0%AF
  + http://bsu-philosophy.wikia.com/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4%D1%8B_%D1%8D%D0%BC%D0%BF%D0%B8%D1%80%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B3%D0%BE_%D0%B8%D1%81%D1%81%D0%BB%D0%B5%D0%B4%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F:_%D0%BD%D0%B0%D0%B1%D0%BB%D1%8E%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5,_%D1%8D%D0%BA%D1%81%D0%BF%D0%B5%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D1%82,_%D1%81%D1%80%D0%B0%D0%B2%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5,_%D0%B8%D0%B7%D0%BC%D0%B5%D1%80%D0%B5%D0%BD%D0%B8%D0%B5
  + http://society.polbu.ru/moiseev_sciencephilo/ch17_i.html
  + http://gtmarket.ru/concepts/6874#t2
  + https://ru.wikipedia.org/wiki/%D0%AD%D0%BA%D1%81%D0%BF%D0%B5%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D1%82


Степин:
Эмпирическое исследование базируется на непосредственном
практическом взаимодействии исследователя с изучаемым объектом.
Оно предполагает
осуществление наблюдений и экспериментальную деятельность. Поэтому средства
эмпирического исследования необходимо включают в себя приборы, приборные установки и
другие средства реального наблюдения и эксперимента.

Эмпирический и теоретический типы познания различаются не только по средствам, но и по
методам исследовательской деятельности. На эмпирическом уровне в качестве основных
методов применяются реальный эксперимент и реальное наблюдение. Важную роль такжеиграют методы эмпирического описания, ориентированные на максимально очищенную от
субъективных наслоений объективную характеристику изучаемых явлений.

Эмпирическое исследование
изучает явления и их корреляции; в этих корреляциях, в отношениях между явлениями оно
может уловить проявление закона. Но в чистом виде он дается только в результате
теоретического исследования.

Рассмотрим вначале внутреннюю структуру эмпирического уровня. Его образуют по меньшей
мере два подуровня: а) непосредственные наблюдения и эксперименты, результатом которых
являются данные наблюдения; б) познавательные процедуры, посредством которых
осуществляется переход от данных наблюдения к эмпирическим зависимостям и фактам.

Научные наблюдения всегда целенаправленны и осуществляются как систематические
наблюдения, а в систематических наблюдениях субъект обязательно конструирует приборную
ситуацию. Эти наблюдения предполагают особое деятельностное отношение субъекта к объекту,
которое можно рассматривать как своеобразную квазиэкспериментальную практику. Что же
касается случайных наблюдений, то для исследования их явно недостаточно. Случайные
наблюдения могут стать импульсом к открытию тогда и только тогда, когда они переходят в
систематические наблюдения.

Все это означает, что наблюдения не являются чистой эмпирией, а несут на себе отпечаток
предшествующего развития теорий.

Переход от данных наблюдения к эмпирическим зависимостям и научному факту предполагает
элиминацию из наблюдений содержащихся в них субъективных моментов (связанных с
возможными ошибками наблюдателя, случайными помехами, искажающими протекание
изучаемых явлений, ошибками приборов) и получение достоверного объективного знания о
явлениях.

Установление этого эмпирического факта потребовало применения целого ряда теоретических
положений (это были сведения из области механики, электродинамики, астрофизики и т.д.).
В обоих рассмотренных случаях факт был получен благодаря интерпретации данных
наблюдения. Эту процедуру не следует путать с процессом формирования теории, которая
должна дать объяснение полученному факту.

Таким образом, при исследовании структуры эмпирического познания выясняется, что не
существует чистой научной эмпирии, не содержащей в себе примесей теоретического. Но это
является не препятствием для формирования объективно истинного эмпирического знания, а
условием такого формирования.
