- титульный лист
- оглавление
- перечень условных обозначений и терминов (?)
- введение (до 3 страниц)
- основная часть:
  - обзор литературы (до 15 страниц)
  - теоретический раздел (10 - 15 страниц)
  - экспериментальных раздел:
    методика проведения экспериментов и анализ полученных результатов (до 35 страниц)
  - заключение:
    оценка полученных результатов или практические предложения для реализации (10-15 страниц)
- заключение
- список использованных источников
- список собственных публикаций
- приложения (?)

Замечания:
+ УДК??? 519.233.22
- выбросить слова "классическая линейная регрессия"

- Нет автореферата.
- Нет выводов, по главам и по работе.
Выводы - это не заключение.
В выводах акцентированно записывается, какие новые научные результаты вы получили, чем они
отличаются от известных и что позволяют по сравнению с известными.
Вам нужно знать (и это должно быть написано), сколько (два, три, пять?)
новых научных результатов вы получили, и в чем они состоят.
В конце каждой главы (за исключением, возможно, обзорной) - свои полученные новые результаты,
в конце работы повторяются дословно суммарные результаты.
Можете причислить себе классификацию стохастических объектов - маленький, но
важный для выполнения сравнений новый научный результат, отсутствовавший до нас в литературе.

- в текст и новые результаты нужно включить также
разработку программ, например, алгоритм (я вам высылал) и программу
симметричной аппроксимации, возможно, других программ общего назначения.



Наименование иллюстрации и пояснительные данные (подрисуночный текст) располагаются по центру страницы.
Пояснительные данные помещают под иллюстрацией, а со следующей строки – слово «Рисунок»,
номер и наименование иллюстрации, отделяя знаком тире номер от наименования.
Точку в конце нумерации и наименований иллюстраций не ставят.
Не допускается перенос слов в наименовании рисунка.
Слово «Рисунок», его номер и наименование иллюстрации печатают полужирным шрифтом,
причем слово «Рисунок», его номер, а также пояснительные данные к нему – уменьшенным на 1–2 пункта размером шрифта.

Значение каждого символа и числового коэффициента следует давать с новой строки.
Первую строку пояснения начинают со слов «где» без двоеточия.

4.9. Сведения об использованных в диссертации источниках приводятся в разделе «Библиографический список»,
включающем подразделы «Список использованных источников» и «Список публикаций соискателя».
Допускается приведение одного и того же источника в библиографическом списке только один раз.
Список использованных источников и список публикаций соискателя формируются в порядке
появления ссылок в тексте диссертации либо в алфавитном порядке фамилий первых авторов и (или) заглавий.
Пример оформления сведений дан в приложении 2.

Во всех случаях, кроме представления на плакатах, магистрант готовит всем членам ГЭК твердые копии иллюстративного графического материала.

* Презентация

- Постановка задачи идентификации (с. 10)
- Классификация стохастических систем (с. 12)
- Критерии и методы идентификации линейных стохастических систем (с. 14)
  - классический критерий - классический метод наименьших квадратов
  - симметричный критерий - метод симметричной аппроксимации
- Постановка задачи исследования
- Идентификация линейных стохастических систем
  - Математическая модель идентифицируемой системы
  - Точность оценивания параметров
  - Точность прогнозирования наблюдений выхода
  - Выводы
- Идентификация нелинейных стохастических систем
  - Методы идентификации нелинейных стохастических систем
  - Математическая модель идентифицируемой системы
  - Точность оценивания параметров
  - Выводы
- Заключение


Графическая
часть по решению выпускающей кафедры может быть представлена на защите
магистерской диссертации в виде электронной презентации с распечаткой
бумажного раздаточного материала для членов ГЭК.

Графический материал, включающий чертежи, схемы, рисунки,
таблицы, графики с основными результатами работы, должен быть представлен
на плакатах или в виде распечатанной электронной версии презентации,
подшитой в приложении.

... электронной версии презентации для демонстрации на
мультимедийном проекторе. В данном случае магистрант готовит всем членам
ГЭК печатные копии иллюстративного графического материала.
5.2 Количество листов (страниц) графического материала

Каждый лист должен иметь заголовок, располагаемый в верхней
части, хорошо читаемый на расстоянии, и порядковый номер в правом верхнем
углу.

5.4 Информация, представленная на каждом листе, должна быть
функционально законченной, иметь подзаголовки разделов, нумерацию
рисунков и формул в пределах данного листа.
